const API={
  async get(path,params={}){const qs=new URLSearchParams(params).toString();const res=await fetch(`/api${path}${qs?"?"+qs:""}`);if(!res.ok)throw new Error(res.status);return res.json();},
  async put(path,body){const res=await fetch(`/api${path}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!res.ok)throw new Error(res.status);return res.json();},
  async post(path,body={}){const res=await fetch(`/api${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!res.ok)throw new Error(res.status);return res.json();},
  async uploadFile(file){const fd=new FormData();fd.append("file",file);const res=await fetch("/api/upload",{method:"POST",body:fd});if(!res.ok)throw new Error(res.status);return res.json();},
  dashboardStats:()=>API.get("/dashboard/stats"),
  dashboardTop:(n=15)=>API.get("/dashboard/top",{limit:n}),
  dashboardTrend:(d=30)=>API.get("/dashboard/trend",{days:d}),
  ownerWorkload:()=>API.get("/dashboard/owner-workload"),
  deptSummary:()=>API.get("/dashboard/dept-summary"),
  getEscalations:(p={})=>API.get("/escalations",p),
  getEscalation:(id)=>API.get(`/escalations/${id}`),
  updateEscalation:(id,d)=>API.put(`/escalations/${id}`,d),
  aiProcess:(id)=>API.post(`/escalations/${id}/ai-process`),
  issueTypes:()=>API.get("/analytics/issue-types"),
  accounts:()=>API.get("/analytics/accounts"),
  resolution:()=>API.get("/analytics/resolution"),
  priorityAge:()=>API.get("/analytics/priority-age"),
  slaPerformance:()=>API.get("/analytics/sla-performance"),
  filters:()=>API.get("/meta/filters"),
  brief:()=>API.get("/morning/brief"),
  intake:(d)=>API.post("/intake",d),
  customAnalysis:(id)=>API.get(`/analysis/${id}`),
  customBrief:(id)=>API.get(`/morning/brief/${id}`),
};
