const AnalyticsView = {
  async render(container) {
    container.innerHTML=`<div class="page-content"><div class="tab-bar mb-24" id="atabs"><div class="tab active" data-tab="issues">Issue Types</div><div class="tab" data-tab="accounts">Top Accounts</div><div class="tab" data-tab="resolution">Resolution</div><div class="tab" data-tab="sla">SLA</div><div class="tab" data-tab="aging">Aging</div></div><div id="acontent"></div></div>`;
    document.getElementById("atabs").addEventListener("click",e=>{ const t=e.target.closest("[data-tab]"); if(!t)return; document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active")); t.classList.add("active"); this.tab(t.dataset.tab); });
    this.tab("issues");
  },
  async tab(name) {
    const el=document.getElementById("acontent"); el.innerHTML=`<div class="loading-row">Loading...</div>`;
    if(name==="issues") await this.issues(el);
    else if(name==="accounts") await this.accounts(el);
    else if(name==="resolution") await this.resolution(el);
    else if(name==="sla") await this.sla(el);
    else if(name==="aging") await this.aging(el);
  },
  async issues(el) {
    const data=await API.issueTypes(); const top=data.slice(0,15);
    el.innerHTML=`<div class="card mb-24"><div class="card-header"><span class="card-title">Issue Volume (Top 15)</span></div><div class="chart-wrap" style="height:${Math.max(top.length*36+60,300)}px"><canvas id="c-ib"></canvas></div></div>
    <div class="card"><div class="card-header"><span class="card-title">Full Breakdown</span></div><div class="table-wrap"><table><thead><tr><th>Issue Type</th><th>Total</th><th>Resolved</th><th>Critical</th><th>SLA Breach</th><th>Avg Delay</th><th>Avg TAT</th></tr></thead><tbody>${data.map(r=>`<tr><td style="font-weight:600;color:var(--text-white)">${Utils.escHtml(r.issue_type)}</td><td class="td-mono">${r.total}</td><td class="td-mono">${r.resolved} <span style="font-size:10px;color:var(--text-muted)">(${r.total?Math.round(r.resolved/r.total*100):0}%)</span></td><td class="td-mono ${r.critical>5?"delay-critical":""}">${r.critical}</td><td class="td-mono ${r.sla_breaches>3?"delay-high":""}">${r.sla_breaches}</td><td class="td-mono ${Utils.delayClass(r.avg_delay)}">${r.avg_delay}d</td><td class="td-mono">${r.avg_tat_hours?Math.round(r.avg_tat_hours)+"h":"—"}</td></tr>`).join("")}</tbody></table></div></div>`;
    ChartRegistry.create("c-ib",{type:"bar",data:{labels:top.map(d=>d.issue_type),datasets:[{label:"Total",data:top.map(d=>d.total),backgroundColor:"rgba(232,86,58,0.6)",borderRadius:3},{label:"Resolved",data:top.map(d=>d.resolved),backgroundColor:"rgba(34,197,94,0.5)",borderRadius:3}]},options:{...Utils.chartDefaults,indexAxis:"y",plugins:{...Utils.chartDefaults.plugins,legend:{display:true,labels:{color:"#555d75",font:{size:11},boxWidth:10,padding:12}}},scales:{x:{...Utils.chartDefaults.scales.x,beginAtZero:true},y:{...Utils.chartDefaults.scales.y,grid:{display:false},ticks:{color:"#8b91a8",font:{size:11}}}}}});
  },
  async accounts(el) {
    const data=await API.accounts();
    el.innerHTML=`<div class="card"><div class="card-header"><span class="card-title">Top 25 Accounts by Escalation Volume</span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Account</th><th>Size</th><th>Industry</th><th>Total</th><th>Escalations</th><th>Open</th><th>Critical</th><th>SLA</th><th>Avg Delay</th><th>Risk</th></tr></thead><tbody>${data.map((r,i)=>{const risk=r.critical>3||r.sla_breaches>5?"Critical":r.critical>1||r.sla_breaches>2?"High":"Low";return`<tr><td class="td-mono" style="color:var(--text-muted)">${i+1}</td><td style="font-weight:600;color:var(--text-white)">${Utils.escHtml(r.account_name)}</td><td>${Utils.sizeBadge(r.account_size)}</td><td style="font-size:12px;color:var(--text-secondary)">${Utils.escHtml(r.industry)}</td><td class="td-mono">${r.total}</td><td class="td-mono">${r.escalations}</td><td class="td-mono ${r.open_escalations>5?"delay-high":""}">${r.open_escalations}</td><td class="td-mono ${r.critical>0?"delay-critical":""}">${r.critical}</td><td class="td-mono ${r.sla_breaches>0?"delay-high":""}">${r.sla_breaches}</td><td class="td-mono ${Utils.delayClass(r.avg_delay)}">${r.avg_delay}d</td><td>${Utils.priorityBadge(risk)}</td></tr>`;}).join("")}</tbody></table></div></div>`;
  },
  async resolution(el) {
    const data=await API.resolution(); const depts=data.map(d=>d.department); const colors=depts.map(d=>Utils.DEPT_COLORS[d]||"#555");
    el.innerHTML=`<div class="charts-grid mb-24"><div class="card"><div class="card-header"><span class="card-title">Resolution Rate %</span></div><div class="chart-wrap" style="height:220px"><canvas id="c-rr"></canvas></div></div><div class="card"><div class="card-header"><span class="card-title">Avg TAT (hours)</span></div><div class="chart-wrap" style="height:220px"><canvas id="c-rt"></canvas></div></div></div>
    <div class="card"><div class="card-header"><span class="card-title">Department Performance</span></div><div class="table-wrap"><table><thead><tr><th>Department</th><th>Total</th><th>Closed</th><th>Open</th><th>Resolution %</th><th>Avg TAT</th><th>SLA Breaches</th></tr></thead><tbody>${data.map(r=>`<tr><td style="font-weight:600;color:var(--text-white)">${Utils.escHtml(r.department)}</td><td class="td-mono">${r.total}</td><td class="td-mono" style="color:var(--low)">${r.closed}</td><td class="td-mono" style="color:var(--blue)">${r.open_count}</td><td><div style="display:flex;align-items:center;gap:8px"><div class="progress-bar" style="width:80px;height:6px;margin:0"><div class="progress-fill ${r.resolution_rate>=60?"fill-low":r.resolution_rate>=40?"fill-medium":"fill-critical"}" style="width:${r.resolution_rate}%"></div></div><span class="td-mono" style="font-size:12px">${r.resolution_rate}%</span></div></td><td class="td-mono">${r.avg_tat_hours?Math.round(r.avg_tat_hours)+"h":"—"}</td><td class="td-mono ${r.sla_breaches>5?"delay-critical":""}">${r.sla_breaches}</td></tr>`).join("")}</tbody></table></div></div>`;
    ChartRegistry.create("c-rr",{type:"bar",data:{labels:depts,datasets:[{data:data.map(d=>d.resolution_rate),backgroundColor:colors.map(c=>c+"99"),borderColor:colors,borderWidth:1,borderRadius:4}]},options:{...Utils.chartDefaults,scales:{x:{...Utils.chartDefaults.scales.x,ticks:{...Utils.chartDefaults.scales.x.ticks,maxRotation:30}},y:{...Utils.chartDefaults.scales.y,beginAtZero:true,max:100,ticks:{...Utils.chartDefaults.scales.y.ticks,callback:v=>v+"%"}}}}});
    ChartRegistry.create("c-rt",{type:"bar",data:{labels:depts,datasets:[{data:data.map(d=>d.avg_tat_hours?Math.round(d.avg_tat_hours):0),backgroundColor:colors.map(c=>c+"66"),borderColor:colors,borderWidth:1,borderRadius:4}]},options:{...Utils.chartDefaults,scales:{x:{...Utils.chartDefaults.scales.x,ticks:{...Utils.chartDefaults.scales.x.ticks,maxRotation:30}},y:{...Utils.chartDefaults.scales.y,beginAtZero:true}}}});
  },
  async sla(el) {
    const data=await API.slaPerformance();
    el.innerHTML=`<div class="kpi-grid kpi-grid-3 mb-24">${data.map(r=>`<div class="kpi-card ${r.priority.toLowerCase()}"><div class="kpi-label">${r.priority}</div><div class="kpi-value ${r.priority.toLowerCase()}">${r.within_sla}</div><div class="kpi-meta">Within SLA · ${r.breached} breached</div><div class="progress-bar mt-8"><div class="progress-fill fill-${r.priority.toLowerCase()}" style="width:${r.total?Math.round(r.within_sla/r.total*100):0}%"></div></div><div style="font-size:10px;color:var(--text-muted);margin-top:4px">${r.total?Math.round(r.within_sla/r.total*100):0}% on-time · avg ${r.avg_delay}d</div></div>`).join("")}</div>
    <div class="card"><div class="card-header"><span class="card-title">SLA Compliance by Priority</span></div><div class="chart-wrap" style="height:240px"><canvas id="c-sla"></canvas></div></div>`;
    ChartRegistry.create("c-sla",{type:"bar",data:{labels:data.map(d=>d.priority),datasets:[{label:"Within SLA",data:data.map(d=>d.within_sla),backgroundColor:"#22c55e99",borderColor:"#22c55e",borderWidth:1,borderRadius:4},{label:"Breached",data:data.map(d=>d.breached),backgroundColor:"#ef444499",borderColor:"#ef4444",borderWidth:1,borderRadius:4}]},options:{...Utils.chartDefaults,plugins:{...Utils.chartDefaults.plugins,legend:{display:true,labels:{color:"#555d75",font:{size:11},boxWidth:10,padding:12}}},scales:{x:{...Utils.chartDefaults.scales.x},y:{...Utils.chartDefaults.scales.y,beginAtZero:true}}}});
  },
  async aging(el) {
    const data=await API.priorityAge();
    el.innerHTML=`<div class="card mb-24"><div class="card-header"><span class="card-title">Escalation Age Distribution</span></div><div class="chart-wrap" style="height:260px"><canvas id="c-age"></canvas></div></div>
    <div class="card"><div class="card-header"><span class="card-title">Aging Breakdown</span></div><div class="table-wrap"><table><thead><tr><th>Age Bucket</th><th>Critical</th><th>High</th><th>Medium</th><th>Low</th><th>Total</th></tr></thead><tbody>${data.map(r=>`<tr><td style="font-weight:600;color:var(--text-white)">${r.bucket}</td><td class="td-mono" style="color:var(--critical)">${r.Critical}</td><td class="td-mono" style="color:var(--high)">${r.High}</td><td class="td-mono" style="color:var(--medium)">${r.Medium}</td><td class="td-mono" style="color:var(--low)">${r.Low}</td><td class="td-mono font-bold">${r.total}</td></tr>`).join("")}</tbody></table></div></div>`;
    ChartRegistry.create("c-age",{type:"bar",data:{labels:data.map(d=>d.bucket),datasets:["Critical","High","Medium","Low"].map(p=>({label:p,data:data.map(d=>d[p]),backgroundColor:Utils.PRIORITY_COLORS[p]+"99",borderColor:Utils.PRIORITY_COLORS[p],borderWidth:1,borderRadius:3}))},options:{...Utils.chartDefaults,plugins:{...Utils.chartDefaults.plugins,legend:{display:true,labels:{color:"#555d75",font:{size:11},boxWidth:10,padding:12}}},scales:{x:{...Utils.chartDefaults.scales.x},y:{...Utils.chartDefaults.scales.y,beginAtZero:true,stacked:true}}}});
  },
};
